### ISSUE TITLE
tons and tons of notifications on every reboot

### ISSUE THREAD

**Issue by deutrino** [SamarthDesai01/RepeatMe#12]
Hello, every time I reboot my phone I get a ton of notifications I've already dismissed, including multiples of ones dismissed days ago. Installed from F-droid, version 1.2.4.

**Comment by SamarthDesai01** [comment]
Hey! 

This issue was fixed with the latest update. Unfortunately, it seems F-droid hasn't built the latest version of the app yet due to some unresolved issue in the build process. If you'd like to grab the latest version you can do so [here](https://github.com/SamarthDesai01/RepeatMe/releases).

Unfortunately, due to the way notifications are being handled on Android, you'll need to do a clean reinstall and recreate any notifications that you'd still like to receive. 

If you'd like more background on this bug you can check out issue #7.

Thank you for using the app!

**Comment by esmoak** [comment]
FYI, F-Droid pushed out an update to 1.2.5 and it is working great.
