### ISSUE TITLE
Feature request: Edit/delete reminder 

### ISSUE THREAD

**Issue by moso** [SamarthDesai01/RepeatMe#2]
As of the current version, I'm not able to edit, view, or easily delete a reminder. It would be a nice feature.

**Comment by SamarthDesai01** [comment]
Thanks for filing a feature request! As of now you can delete a reminder simply by swiping the card to the left or right.

I initially didn't implement editing features because I assumed most people would just recreate a reminder and delete the old one. But since I now know there's demand for it I'll start working on it as soon as I have more time on my hands 👍

**Comment by senpl** [comment]
Any progress on that, or maybe pull request suggestions ???

**Comment by SamarthDesai01** [comment]
Haven't had the chance to get into this one yet, but if you want to look into this go right ahead! Another feature that I haven't figured out is an archived task list or the ability to rearrange tasks by holding and dragging them across the screen instead of using one of the sorting options. Could be something interesting to look into!
