### ISSUE TITLE
Reminders don't fully delete 

### ISSUE THREAD

**Issue by esmoak** [SamarthDesai01/RepeatMe#7]
Huawei, Android 8.0

Steps to reproduce:

Create reminder then swipe to delete.

Restart phone and I get notifications for reminders which were deleted. 

The reminders screen shows blank since they were swiped away.

**Comment by SamarthDesai01** [comment]
Hi Esmoak! 

This has been a known issue for a while and I'm sorry you've encountered it so soon. Notification scheduling is mostly handled by a third party plugin (since Flutter lacks cross platform notification support natively) which has strange behavior upon restarts and OS updates. I'm not sure how exactly to approach this issue since I don't know where exactly the plugin is scheduling notifications to cause such behavior. 

I'm also very busy with classes right now so I'm pretty short on time, but if you or anyone you know would like to contribute I'm more than happy to merge any PRs that have bug fixes or new features!

Again I'm really sorry you had to deal with this, but thank you for using the app!

**Comment by esmoak** [comment]
Thanks for the quick response. 

I wish I could, but I'm unable to contribute.

Thank you.

**Comment by SamarthDesai01** [comment]
Good news!

I did a bit more research and it looks like the notification plugin had pushed out an update a little while ago addressing this exact issue. Unfortunately in the time between now and this app's most recent update another plugin I had been using was taken down. This will increase the time it takes to push out a fix as I now need to find a suitable replacement for it and integrate it into the app. 

(Hopefully) I can roll out a fix within a couple of days.

**Comment by esmoak** [comment]
That's awesome! And best wishes on your studies.

Thanks again.

**Comment by SamarthDesai01** [comment]
Just pushed out an update to fix this! 

Unfortunately, notifications created before this update are still susceptible to the bug you encountered so the only way to get rid of those annoying notifications is a clean reinstall. Sadly this is still out of my control so I can't migrate old notifications to be displayed in the same way as the new ones. 

https://github.com/SamarthDesai01/RepeatMe/releases/tag/v1.2.5

**Comment by esmoak** [comment]
Thank you. I will check this out soon.

**Comment by SamarthDesai01** [comment]
Let me know if you continue to encounter the issue.

**Comment by esmoak** [comment]
Thanks again. Going to close this because it appears fixed. 

Also, F-Droid put out the newest version on 2/18. Tested and it's working great.
