### ISSUE TITLE
Any change in the color picker ?

### ISSUE THREAD

**Issue by realrufans** [SamarthDesai01/RepeatMe#9]
Good day , I really wanna say a big thank you for the latest update.

But I have been wondering, what went wrong with the old Color picker.  I guess, the colors were too tiny to pick ?🤔 

And I tried downgrading my version to check out the old Color picker but I'm still getting the updated picker. What went wrong ?
![Screenshot_20190212-041432.png](https://cdn.steemitimages.com/DQmTPGPP4RqVvU2v6VtYtSyJhMHPv1xAJiMwSHK8dDco243/Screenshot_20190212-041432.png)

Thank you.

**Comment by SamarthDesai01** [comment]
Hi! 

The reason the color picker had to be changed was because the old color picker was no longer available online on Pub. Because of this, I was unable to update any other packages such as the one I use for delivering notifications which meant I couldn't fix a bug another user had encountered. As a result, I needed to find a new replacement for the color picker so that I could continue to maintain the app. 

Also when installing the older version, double check that you're installing v1.2.4 or below and that you've fully uninstalled the latest version before doing so. That should most likely fix your issue! 

Thanks so much for using the app!

**Comment by SamarthDesai01** [comment]
Also if you're just interested in what the old color picker looked like, you can find a screenshot of it on the Google Play listing of the app. 

[https://play.google.com/store/apps/details?id=com.samarthdesai.repeatme](https://play.google.com/store/apps/details?id=com.samarthdesai.repeatme)

**Comment by realrufans** [comment]
Okay thank you ..let me try installing older version again.

**Comment by realrufans** [comment]
Thanks it worked. 
One more question: What do you mean by Pub?

Edit: You can just give me a link to read ..thanks

**Comment by SamarthDesai01** [comment]
Awesome! 

Here's what Pub is: [https://pub.dartlang.org/](https://pub.dartlang.org/)

**Comment by realrufans** [comment]
Thank you for your time.. I will surely come back to contribute. Stay blessed.
